import { arraySidebar } from "vuepress-theme-hope";

export default arraySidebar([
  "",
  {
    text: "基础知识",
    icon: "seedling",
    prefix: "foundation/",
    collapsible: true,
    children: ["representation-learning-model", "linear-vs-nonlinear"],
  },
  {
    text: "监督表示学习",
    icon: "graduation-cap",
    prefix: "supervised/",
    collapsible: true,
    children: ["ImageNet 预训练范式", "监督表示的特性"],
  },
  {
    text: "自监督表示学习",
    icon: "rotate",
    prefix: "self-supervised/",
    collapsible: true,
    children: [
      "生成式（Generative）",
      "对比式（Contrastive）",
      "非对比式 _ 冗余消除（Non-contrastive）",
      "三大范式的对比",
    ],
  },
  {
    text: "传统无监督表示学习",
    icon: "circle-nodes",
    prefix: "unsupervised/",
    collapsible: true,
    children: ["经典无监督方法", "流形学习"],
  },
  {
    text: "半监督、弱监督表示学习",
    icon: "tags",
    prefix: "semi-supervised/",
    collapsible: true,
    children: ["半监督核心方法"],
  },
  {
    text: "度量学习",
    icon: "ruler-combined",
    prefix: "metric/",
    collapsible: true,
    children: ["度量学习的核心思想", "代表损失函数与方法"],
  },
  {
    text: "迁移表示学习",
    icon: "arrow-right-arrow-left",
    prefix: "transfer/",
    collapsible: true,
    children: ["预训练 + 微调范式", "迁移学习的调式"],
  },
  {
    text: "多任务表示学习",
    icon: "list-check",
    prefix: "multitask/",
    collapsible: true,
    children: ["多任务学习的核心思想", "关键挑战"],
  },
  {
    text: "架构范式对照",
    icon: "sitemap",
    prefix: "architecture/",
    collapsible: true,
    children: [
      "编码器-解码器家族树",
      "核心对照：跳跃连接（Skip Connection）",
      "完整的归属链",
    ],
  },
  {
    text: "理解笔记",
    icon: "note-sticky",
    prefix: "notes/",
    collapsible: true,
    children: [
      "自编码器的本质：信息瓶颈",
      "对比学习的本质：拉近正推开负",
      "非对比式方法的启示：负样本不是必须的",
      "线性 vs 非线性：一个激活函数的差距",
      "AE vs U-Net：同一个父亲，不同的母亲",
      "自监督表示学习三大范式速记",
    ],
  },
]);
